print("\tExercise 1\nEnter the name of your pet, then its age")
pet_name = input()
pet_age = input()
print(pet_name, pet_age)
print("\tExercise 2\nOne by one enter the name of the main stages of human evolution")
fst_stage = input()
scnd_stage = input()
thrd_stage = input()
frth_stage = input()
ffth_stage = input()
print(fst_stage, scnd_stage, thrd_stage, frth_stage, ffth_stage, sep="=>")