print("\tExercise 1\nВведите вид животного, имя, затем возрост:")
pet_kind = input()
pet_name = input()
pet_age = input()
print("Это", pet_kind, "по кличке", pet_name + '.', "Возраст:", pet_age, "года.")

print("\tExercise 2\nOne by one enter the name of the main stages of human evolution")
fst_stage = input()
scnd_stage = input()
thrd_stage = input()
frth_stage = input()
ffth_stage = input()
print(fst_stage, scnd_stage, thrd_stage, frth_stage, ffth_stage, sep="=>")
